rubocop:
  version: 1.5.2
  config_file: .rubocop.yml
haml:
  config_file: .haml-lint.yml
scss:
  enabled: false
sass-lint:
  enabled: false
eslint:
  enabled: false
  config_file: .eslintrc
  version: 7.7.0
jshint:
  enabled: false
