AllCops:
  TargetRubyVersion: 2.3.5
  TargetRailsVersion: 5.0
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'lib/templates/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
