queues:
  default: <%= RadicalConfig.sqs_queue_url!(:default) %>
  mailers: <%= RadicalConfig.sqs_queue_url!(:default) %>
  sms: <%= RadicalConfig.sqs_queue_url!(:default) %>
  active_storage_analysis: <%= RadicalConfig.sqs_queue_url!(:default) %>
  active_storage_purge: <%= RadicalConfig.sqs_queue_url!(:default) %>
