development:
  adapter: postgresql
  encoding: unicode
  database: radbear_rails_development

test:
  adapter: postgresql
  encoding: unicode
  database: radbear_rails_test

production:
  adapter: postgresql
  encoding: unicode
  database: radbear_rails_production