test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= RadicalConfig.aws_s_3_access_key_id! %>
  secret_access_key: <%= Rails.application.credentials.aws[:s_3][:secret_access_key] %>
  region: <%= Rails.application.credentials.aws[:s_3][:region] %>
  bucket: <%= Rails.application.credentials.aws[:s_3][:bucket] %>
